/**
 * HomepageDocenteIIFE script 
 */

// Avoid letiables ending up in the global scope
{
	// letiables describing the view components
	let pageOrchestrator = new PageOrchestrator(); // main controller
	//let docente;
	
	let docente;
	let scaglioni;
	let appelli;
	let esami;
	let verbali;
	let verbaleInfo;
	let formEsame;
	let inserimentoMultiplo;
		
	// URLs to access Java servlets
	let URL_DOCENTE = "GetDocente";
	let URL_APPELLI = "GetAppelliByScaglione";
	let URL_ESAMI_BY_APPELLO = "GetEsamiByAppello";
	let URL_ESAME = "GetEsame";
	let URL_PUBBLICA = "Pubblica";
	let URL_VERBALIZZA = "Verbalizza";
	let URL_VERBALI = "GetVerbaliByAppello";
	let URL_ASSIGN_GRADE = "AssignGrade";
	let URL_ASSIGN_MULT_GRADE = "AssignMultGrade";
	let URL_VERBALE_INFO = "GetVerbaleInfoByIdVerbale";
	
	// Handle page behaviour onLoad
	window.addEventListener("load", () =>
	{
		// Security check for docente
		makeCall("GET", URL_DOCENTE, null,
		        // callback function
		        function(req)
		        {
			    	if (req.readyState == XMLHttpRequest.DONE) // == 4
			    	{
						let message = req.responseText;
			            if (req.status == 200) 
			            {
							// if everything is fine, setup page view
							docente = JSON.parse(message);
							pageOrchestrator.start(); 
						}
						else
			            {
							window.location.href = "index.html";
							return;
						}
			      	}
		        }
      		);
		
 	}, false);
		  
	function PageOrchestrator()
  	{   
		// Behaviour on start
	    this.start = function()
	    {
			alertContainer = document.getElementById("alert");
			
			// List of appelli
			appelli = new Appelli
			(
				{ 	// many parameters, wrap them in an object
			        alert: document.getElementById("no_appelli_alert"),
			        appelli_header: document.getElementById("header_appelli"),
			        appelli_table: document.getElementById("table_appelli"),
			        appelli_table_body: document.getElementById("table_appelli_body"),
				}
			);
			
			// List of esami when selecting an appello
			esami = new Esami
			(
				{
			        alert: document.getElementById("no_esami_alert"),
			        esami_master_div: document.getElementById("master_div_esami"),
			        esami_header_info: document.getElementById("header_esami_info"),
			        esami_header: document.getElementById("header_esami"),
			        esami_table: document.getElementById("table_esami"),
			        esami_table_body: document.getElementById("table_esami_body"),
			        pubblica_button: document.getElementById("pubblica_button"),
			        verbalizza_button: document.getElementById("verbalizza_button"),
			        inserimento_multiplo_button: document.getElementById("inserimento_multiplo_button"),
			        orchestrator: this
				}
			)
			
			// Form esame when selecting an esame to modify
			formEsame = new FormEsame
			(
				{
					form_esame: document.getElementById("form_esame"),
					form_esame_table: document.getElementById("form_esame_table"),
					assign_button: document.getElementById("assign_button"),
					voto_text: document.getElementById("voto_text"),
				}
			);
			
			// List of verbali when selecting an esame 
			verbali = new Verbali
			(
				{
					verbali_table: document.getElementById("verbali_table"),
					verbali_table_body: document.getElementById("verbali_table_body")
				}
			);
			
			// Infos of verbale selected between verbali
			verbaleInfo = new VerbaleInfo
			(
				{
					verbale_div: document.getElementById("verbale_div"),
					verbale_table: document.getElementById("verbale_table"),
					studenti_verbale_table: document.getElementById("studenti_verbale_table"),
					studenti_verbale_table_body: document.getElementById("studenti_verbale_table_body")
				}
			);
			
			// Modal windows to assign a grade to multiple yet to assess exams
			inserimentoMultiplo = new InserimentoMultiplo
			(
				{	
					modalDiv: document.getElementById("modalDiv"),
					voto_mult: document.getElementById("voto_mult"),
					assign_mult_button: document.getElementById("assign_mult_button"),
					ins_mult_table: document.getElementById("ins_mult_table"),
					ins_mult_table_body: document.getElementById("ins_mult_table_body"),
					closeButton: document.getElementById("closeButton"),
				}
			);
			
			// On load, show a default scaglione
			this.refresh();
			
			// Setup of interactive buttons related to every component
			esami.init();
			formEsame.init();
			inserimentoMultiplo.init();
			
			// Shows for the first time page body (hidden so far)
			document.body.style.display = "block";
			
			// Scaglioni component handled differently a generated by Thymeleaf
			scaglioni = new Scaglioni(alertContainer, document.getElementById("table_scaglioni_body"), this);
			scaglioni.addLinks(this);
	    };
	    
	    // Brings page to its initial state
	    this.refresh = function(id_scaglione)
		{
			appelli.reset();
			esami.reset();
			formEsame.reset();
			verbali.reset();
			verbaleInfo.reset();
			inserimentoMultiplo.reset();
			
			// finds default scaglione at first refresh
			if (id_scaglione == undefined)
			{
				id_scaglione = document.querySelector(".scaglioneNomeTable").getAttribute("id_scaglione");
			}
			
			appelli.show(id_scaglione);
		}; 
		
		// handles contextual esami showing
		this.showEsami = function(id_appello)
		{
			verbaleInfo.reset();
			formEsame.reset();
			inserimentoMultiplo.reset();
			
			esami.show(id_appello);
			verbali.show(id_appello);
		}
		
		// handles contextual form esame showing
		this.showFormEsame = function(idAppello, matricolaStudente)
		{
			verbali.reset();
			verbaleInfo.reset();
			
			formEsame.show(idAppello, matricolaStudente);
		}
		
		// handles contextual verbali showing
		this.showVerbali = function(idAppello)
		{
			formEsame.reset();
			verbaleInfo.reset();
			inserimentoMultiplo.reset();
			
			verbali.show(idAppello);
		}
		
		// handles contextual verbale info showing
		this.showVerbaleInfo = function(idVerbale)
		{
			formEsame.reset();
			inserimentoMultiplo.reset();
			
			verbaleInfo.show(idVerbale);
		}
		
		// handles contextual inserimento multiplo showing
		this.showInserimentoMultiplo = function(idAppello)
		{
			inserimentoMultiplo.show(idAppello);
		}
 	}
	  
	// Component that handles the Scaglioni Table
	function Scaglioni(_alert, scaglioni_table_body, _orchestrator)
	{	
		let self = this;
		
		this.alert = _alert;
	    this.scaglioni_table_body = scaglioni_table_body;
	    this.orchestrator = _orchestrator;

	    this.addLinks = function(orchestrator)
	    {
	    	let elems = self.scaglioni_table_body.getElementsByClassName("scaglioneNomeTable");
	    	for(let i=0; i < elems.length; i++){
				elems[i].addEventListener('click', (event) => {
		        	orchestrator.refresh(event.target.getAttribute("id_scaglione"));
	      		});
			}
	    };
    }
    
    function Appelli(options)
    {
		let self = this;
		
		// Alert that pops up when there are no appelli related to selected scaglione
	    this.alert = options['alert'];
	    
	    // HTML elements of the component
	    this.appelli_table = options['appelli_table'];
	    this.appelli_table_body = options['appelli_table_body'];
	    this.appelli_header = options['appelli_header'];
	    
		// Resets view
	    this.reset = function()
	    {
	    	self.appelli_table.style.display = "none";
	    };
	    
	    // Hides component on start

		// Show component function
	    this.show = function(scaglioneid)
	    {	    	
	    	//Associated servlet address
	    	let address = URL_APPELLI + '?id_scaglione=' + scaglioneid;
	    	this.appelli_header.textContent = scaglioneid;
	    	let message;	   
	    	let areThereAppelli; 	
	    	
	    	//get appelli by scaglione
	      	makeCall("GET", address, null,
	        	function(req)
	        	{
	          		if (req.readyState == XMLHttpRequest.DONE)
	          		{
	            		message = req.responseText;
			            if (req.status == 200)
			            {
				        	let appelliToShow = JSON.parse(message);
				        	
				        	if (appelliToShow.length == 0)
			              	{
								// Show empty appelli list alert
								areThereAppelli = 0;
			              	}
			              	else
			              	{
								areThereAppelli = 1;
								// Show appelli list
						    	self.update(appelliToShow);
							}
							self.showContent(areThereAppelli);
			            }
		                else
		                {
							alert(message);
			            }
	          		}
        		}
	      	);
	    };

		// Builds appelli list
	    this.update = function(appelliToShow)
	    {
			let self = this;
			
	      	let row;
	   		this.appelli_table_body.innerHTML = ""; // Empty the table body
		    
		    appelliToShow.forEach(function(appello)
		    {
		        row = document.createElement("tr");
		        
		        createTD(row, appello.id);  
		        createLinkTD(row, appello.date, appello.id, esami);
		        
		        self.appelli_table_body.appendChild(row);
	      	});
	    };
	    
	    // Helper function to show content.
	    // If there's not one a message is printed
	    this.showContent = function(isValid)
	    {
			if (isValid)
			{
				self.appelli_table.style.display = "inline-table";
		    	self.alert.style.display = "none";
			}
			else
			{
				self.appelli_table.style.display = "none";
				self.alert.textContent = "Non ci sono ancora appelli disponibili per questo scaglione";
				self.alert.style.display = "inline-block";
			}
		};
	}
	
	function Esami(options)
    {
		let self = this;
		
	    this.alert = options['alert'];
	    
	    this.esami_master_div = options['esami_master_div'];
	    
	    this.esami_table = options['esami_table'];
	    this.esami_table_body = options['esami_table_body'];
	    this.esami_header_info = options['esami_header_info'];
	    this.esami_header = options['esami_header'];
	    
	    this.button_pubblica = options['pubblica_button'];
	    this.button_verbalizza = options['verbalizza_button'];
	    this.button_inserimento_multiplo = options['inserimento_multiplo_button'];
	    
	    this.orchestrator = options['orchestrator'];
	    this.comparatorType; //type of the currently selected column
	    this.sortInverted = false; //true if the sorting should be inverted for the selected column
	    this.selectedSortCol; //index of the currently selected column
	    
	    this.reset = function()
	    {
	    	self.esami_master_div.style.display = "none";
	    };
	    
	    //called at initialization in order to add the events
	    this.init = function()
	    {
			self.createPubblicaBtnEvent(); // Adds pubblica event for button
			self.createVerbalizzaBtnEvent(); // Adds verbalizza event for button
			self.createSortTableLinks(); // Adds sort event
			self.createInserimentoMultiploBtnEvent(); // Adds inserimento multiplo event for button
		}
		
		//adds sort events to the header
		this.createSortTableLinks = function()
		{
			let elems = self.esami_header.getElementsByTagName("th");
	    	for(let i=0; i < elems.length; i++){
				//add sort event for every header element
				elems[i].addEventListener('click', (event) =>
				{
					//get header and corresponding column
					let headers = self.esami_header.getElementsByTagName("th");
					let col = Array.from(headers).indexOf(event.target.parentNode);
					
					//get the type of the selected column (int, voto, string). this changes how we sort the elements
					comparatorType = event.target.parentNode.getAttribute("comparatorType");
					
					//sort rows
					self.sortRows(col, comparatorType);
	      		});
			}
		}
		
		this.sortRows = function(col, comparatorType)
		{
			self.comparatorType = comparatorType;
			
			//if we select the same column twice we should invert the sorting
			if ((typeof self.selectedSortCol !== 'undefined') && col === self.selectedSortCol)
				self.sortInverted = !self.sortInverted;
			else
			{
				self.sortInverted = false;
				self.selectedSortCol = col;
			}
			
			//get rows from table
			let rows = Array.from(self.esami_table_body.querySelectorAll(`tr`));
			
			rows.sort((r1, r2) => {
			    let t1 = r1.cells[col].textContent;
			    let t2 = r2.cells[col].textContent;
			    
			    //compare the two given rows and return 1, -1 or 0
			    let comparatorResult = self.comparator(t1, t2, self.comparatorType);
			    
			    //if sort is inverted we invert the result from the comparator
			    if(self.sortInverted) comparatorResult = comparatorResult * -1;
			    
			    return comparatorResult;
			  });
		  //update the table with the sorted values
		  rows.forEach(row => self.esami_table_body.appendChild(row));
		}
		
		//compares two elements of type "type" and returns 1, -1, 0
		this.comparator = function(a, b, type)
		{
			let sortOrder;
			switch(type)
			{
				case "string": return a.localeCompare(b);
				case "int": return parseInt(a)<parseInt(b) ? -1 : 1;
				case "voto":
					sortOrder = ['<vuoto>','Assente','Rimandato','Riprovato','18','19','20','21','22','23','24','25','26','27','28','29','30','30 e lode'];
					return sortOrder.indexOf(a)<sortOrder.indexOf(b) ? -1 : 1;
				case "stato":
					sortOrder = ['Non inserito','Inserito','Pubblicato','Rifiutato','Verbalizzato'];
					return sortOrder.indexOf(a)<sortOrder.indexOf(b) ? -1 : 1;
			}
		}
		
		this.createPubblicaBtnEvent = function()
		{
		    self.button_pubblica.addEventListener("click", (event) =>
			{
				event.preventDefault();
				
				let id_appello = event.target.getAttribute("id_appello");
				
				let address = URL_PUBBLICA + "?id_appello=" + id_appello;
				
				makeCall("GET", address, null,
	        	function(req)
		        	{
		          		if (req.readyState == XMLHttpRequest.DONE)
		          		{
							if (req.status == 200)
							{
								message = req.responseText;
			            		if(message == "No exams to publish") // No exams case handling
					            {
									alert("Non ci sono esami da pubblicare.");
								}
					            else // Default case handling
					            {
						        	// Message carries the amount of grades published
						        	message = parseInt(message);
						        	
						        	if (message == '1')
						        	{
										alert("Hai pubblicato con successo un voto dell'appello di id: " + id_appello + ".");
									}
									else
									{
										alert("Hai pubblicato con successo " + message + " voti dell'appello di id: " + id_appello + ".");
									}
					            }
					            pageOrchestrator.showEsami(id_appello);
							}
							else
								alert(req.responseText);
		          		}
	        		}
        		);
			}, false);
		}
			
		this.createVerbalizzaBtnEvent = function()
		{
			this.button_verbalizza.addEventListener("click", (event) =>
			{
				event.preventDefault()
				
				let id_appello = event.target.getAttribute("id_appello");
				let address = URL_VERBALIZZA + "?id_appello=" + id_appello;
				let newVerbale;
				
				makeCall("GET", address, null,
        			function(req)
	        		{
		          		if (req.readyState == XMLHttpRequest.DONE)
		          		{
							message = req.responseText;
							
							if (req.status == 200)
							{
			            		if(message == "No exams to verbalize") // No exams case handling
					            {
									alert("Non ci sono esami da verbalizzare.");
									pageOrchestrator.showEsami(id_appello);
									return;
								}
					            else 
					            {
									newVerbale = JSON.parse(message);
						        	
						        	if (newVerbale.numStudentiDaVerbalizzare == 1)
						        	{
										alert("Hai verbalizzato con successo un voto dell'appello di id: " + id_appello + ".");
									}
									else
									{
										alert("Hai verbalizzato con successo " + newVerbale.numStudentiDaVerbalizzare + " voti dell'appello di id: " + id_appello + ".");
									}
									pageOrchestrator.showEsami(id_appello);
					            	pageOrchestrator.showVerbaleInfo(newVerbale.idVerbale);
					            }
							}
							else
							{
								alert(message);
							}
	          			}
        			}
    			);
			}, false);
		}
		
		this.createInserimentoMultiploBtnEvent = function()
		{
			this.button_inserimento_multiplo.addEventListener("click", (event) =>
			{
				event.preventDefault();
				
				let id_appello = event.target.getAttribute("id_appello");
				
				pageOrchestrator.showInserimentoMultiplo(id_appello); // show modal window on button click	
			}, false);
		}

	    this.show = function(appelloid)
	    {
	    	let self = this;
	    	
	    	let address = URL_ESAMI_BY_APPELLO + '?id_appello=' + appelloid;
	    	let message;
	    	
	    	let esamiToShow;
	    	
	      	makeCall("GET", address, null,
	        	function(req)
	        	{
	          		if (req.readyState == XMLHttpRequest.DONE)
	          		{
	            		message = req.responseText;
			            if (req.status == 200)
			            {
				        	esamiToShow = JSON.parse(message);
				        	
				        	verbali.show(appelloid);
				        	
				        	if (esamiToShow.length == 0)
			              	{
								self.showContent(0);
			              	}
			              	else
			              	{
						    	self.update(esamiToShow); // self is the object on which the function
						    	
						    	// Sets header content
						    	self.esami_header_info.innerHTML = appelloid;
						    	
						    	// Set attribute to contextual buttons
								self.button_pubblica.setAttribute("id_appello", appelloid);
								self.button_verbalizza.setAttribute("id_appello", appelloid);
								self.button_inserimento_multiplo.setAttribute("id_appello", appelloid);
								
						    	self.showContent(1);
							}
							
							self.esami_master_div.style.display = "block";
			            }
			            else
			            	alert(req.responseText);
	          		}
        		}
	    	);
	    };

	    this.update = function(esamiToShow)
	    {
	      	let row;
	   		//this.esami_table_body.innerHTML = ""; // empty the table body
	   		emptyElementContent(this.esami_table_body);
		    
		    // build updated list
		    esamiToShow.forEach(function(esame)
		    {
		        row = document.createElement("tr");
		        
		        createTD(row, esame.matricola_studente);
		        createTD(row, esame.cognome + ' ' + esame.nome);
		        createTD(row, esame.email);
		        createTD(row, esame.corso_di_laurea);
		        createTD(row, esame.voto);
		        createTD(row, esame.desc_esito);
		        
		        if (self.isEsameModifiable(esame))
		        {
					self.createEditButton(row, esame.id_appello, esame.matricola_studente);
				}
				else
				{
					createTD(row);
				}
		        
		        self.esami_table_body.appendChild(row);
	      	});
	    };
	    
	    this.showContent = function(isValid)
	    {
			if (isValid)
			{
				self.alert.style.display = "none";
		    	self.esami_table.style.display = "table";
			}
			else
			{
				self.esami_table.style.display = "none";
				self.alert.style.display = "block";
			}
		};
	    
	    this.isEsameModifiable = function(esame)
	    {
			let esamiModificabili = ["Inserito", "Non inserito"];
			let desc_esito = esame.desc_esito;
			
			for (let i = 0; i < esamiModificabili.length; i++)
			{
				if (desc_esito == esamiModificabili[i]) return true;
			}
			return false;
		}
		
		// Append Modifica button to every row of esami table.
		this.createEditButton = function(row, idAppello, matricolaStudente)
		{
			let linkcell, buttonCell;
			
			linkcell = document.createElement("td");
			linkcell.setAttribute("class", "blueTable");
			
			buttonCell = document.createElement("button");
			buttonCell.innerHTML = "Modifica";
			
			linkcell.appendChild(buttonCell);
			
			buttonCell.setAttribute("id_appello", idAppello);
			buttonCell.setAttribute("matricola_studente", matricolaStudente);
			buttonCell.addEventListener("click", (event) =>
			{
				let idAppello = event.target.getAttribute("id_appello");
				let matricolaStudente = event.target.getAttribute("matricola_studente");
			  	pageOrchestrator.showFormEsame(idAppello, matricolaStudente);
			}, false);
			row.appendChild(linkcell);	
		};
	}
	
	function FormEsame(options)
    { 
		let self = this;
		
	    this.form_esame = options['form_esame'];
	    this.form_esame_table = options['form_esame_table'];
	    this.assign_button = options['assign_button'];
	    this.voto_text = options['voto_text'];
	    
	    this.reset = function()
	    {
			self.form_esame.style.display = "none";
		}

	    this.show = function(idAppello, matricolaStudente)
	    {
	    	let esame;
	    	
	    	let address = URL_ESAME + '?id_appello=' + idAppello + '&matricola=' + matricolaStudente;
	    	makeCall("GET", address, null,
	        	function(req)
	        	{
	          		if (req.readyState == 4)
	          		{
	            		message = req.responseText;
			            if (req.status == 200)
			            {
				        	esame = JSON.parse(message);
				        	
				        	//if object is empty
				        	if (Object.keys(esame).length === 0)
			              	{
								self.form_esame.style.display = "none";
			                	return;
			              	}
			              	else
			              	{
						    	self.update(esame);
						    	self.form_esame.style.display = "inline-table";
							}
			            }
			            else
			            	alert(req.responseText);
	          		}
        		}
	      	);
	    };

	    this.update = function(esame)
	    {	
	   		emptyElementContent(self.form_esame_table);
		    
		    createDetailTR(self.form_esame_table, "Matricola", esame.matricola_studente);
		    createDetailTR(self.form_esame_table, "Nome", esame.nome);
		    createDetailTR(self.form_esame_table, "Cognome", esame.cognome);
		    createDetailTR(self.form_esame_table, "Email", esame.email);
		    createDetailTR(self.form_esame_table, "Corso di laurea", esame.corso_di_laurea);
		    createDetailTR(self.form_esame_table, "Stato esito", esame.desc_esito);
		    
		    self.assign_button.setAttribute("id_appello", esame.id_appello);
		    self.assign_button.setAttribute("matricola_studente", esame.matricola_studente);
	    };
	    
	    this.init = function()
	    {
			self.createAssegnaVotoBtnEvent();
		}
	    
	    this.createAssegnaVotoBtnEvent = function()
		{
			this.assign_button.addEventListener("click", (event) =>
			{
				event.preventDefault();
				
				let idAppello = event.target.getAttribute("id_appello");
				let matricolaStudente = event.target.getAttribute("matricola_studente");
				
				let newVoto = self.voto_text.value;
				
				let address = URL_ASSIGN_GRADE + "?id_appello=" + idAppello
					+ "&matricola_studente=" + matricolaStudente
					+ "&voto=" + newVoto;
				
				makeCall("GET", address, null,
	        	function(req)
		        	{
		          		if (req.readyState == XMLHttpRequest.DONE)
		          		{
		            		message = req.responseText;
				            if (req.status == 200) // Default case handling
				            {
					        	alert("Hai assegnato con successo un nuovo voto\na " + matricolaStudente + ".");
					        	pageOrchestrator.showEsami(idAppello);
				            }
				            else
				            	alert(req.responseText);
		          		}
	        		}
	    		);
			}, false);
		}
	}
	
	function Verbali(options)
    { 	
		let self = this;
		
	    this.verbali_table = options['verbali_table'];
	    this.verbali_table_body = options['verbali_table_body'];
	    
	    this.reset = function()
	    {
			self.verbali_table.style.display = "none";
		}

	    this.show = function(appelloid)
	    {
	    	let address = URL_VERBALI + '?id_appello=' + appelloid;
	    	let verbaliToShow;
	    	let message;
	    	
	      	makeCall("GET", address, null,
	        	function(req)
	        	{
	          		if (req.readyState == XMLHttpRequest.DONE)
	          		{
	            		message = req.responseText;
			            if (req.status == 200)
			            {
				        	verbaliToShow = JSON.parse(message);
				        	
				        	if (verbaliToShow.length == 0)
			              	{
								self.reset();
			                	return;
			              	}
			              	else
			              	{
						    	self.update(verbaliToShow);
						    	self.verbali_table.style.display = "inline-table";
							}
			            }
			            else
			            	alert(req.responseText);
	          		}
				}
	      	);
	    };

	    this.update = function(verbaliToShow)
	    {
			let row;
		   
		   	emptyElementContent(self.verbali_table_body);
		    
		    verbaliToShow.forEach(function(verbale)
		    {
		        row = document.createElement("tr");
		        
		        createLinkTD(row, verbale.id, verbale.id, verbaleInfo)
		        createTD(row, verbale.datetime);
		        
		        self.verbali_table_body.appendChild(row);
	      	});
	    };
	}
	
	function VerbaleInfo(options)
    { 
		let self = this;
		
		this.verbale_div = options['verbale_div'];
		this.verbale_table = options['verbale_table'];
		this.studenti_verbale_table = options['studenti_verbale_table'];
		this.studenti_verbale_table_body = options['studenti_verbale_table_body'];
	    
	    this.reset = function()
	    {
			this.verbale_div.style.display = "none";
		}

	    this.show = function(id_verbale)
	    {
	    	let address = URL_VERBALE_INFO + '?id_verbale=' + id_verbale;
	    	let message;
	    	let verbaleInfoToShow;
	    	
	      	makeCall("GET", address, null,
	        	function(req)
	        	{
	          		if (req.readyState == XMLHttpRequest.DONE)
	          		{
	            		message = req.responseText;
			            if (req.status == 200)
			            {
				        	verbaleInfoToShow = JSON.parse(message);
				        	
					    	self.update(verbaleInfoToShow);
					    	this.verbale_div.style.display = "inline-table";
			            }
			            else
			            	alert(req.responseText);
	          		}
        		}
	      	);
	    };

	    this.update = function(verbaleInfoToShow)
	    {
			emptyElementContent(self.verbale_table);
			emptyElementContent(self.studenti_verbale_table_body);
			
			createDetailTR(self.verbale_table, "ID verbale", verbaleInfoToShow.verbale.id);
		    createDetailTR(self.verbale_table, "ID appello d'esame", verbaleInfoToShow.verbale.id_appello);
		    createDetailTR(self.verbale_table, "Nome insegnamento", verbaleInfoToShow.verbale.nome_insegnamento);
		    createDetailTR(self.verbale_table, "Data creazione", verbaleInfoToShow.verbale.datetime);
		   
		    verbaleInfoToShow.esami.forEach(function(esame)
		    { // self visible here, not this
		        row = document.createElement("tr");
		        
		        createTD(row, esame.matricola_studente);
		        createTD(row, esame.voto);
		        
		        self.studenti_verbale_table_body.appendChild(row);
	      	});
	    };
	}
	
	function InserimentoMultiplo(options)
	{	
		let self = this;
		
		this.modalDiv = options['modalDiv'];
		this.voto_mult = options['voto_mult'];
		this.assign_mult_button = options['assign_mult_button'];
		this.ins_mult_table = options['ins_mult_table'];
		this.ins_mult_table_body = options['ins_mult_table_body'];
		this.closeButton = options['closeButton'];
		
		// List of matricole checked for multiple assignment
		this.matricoleChecked = [];
		
		this.reset = function()
		{
			self.modalDiv.style.display = "none";
			self.voto_mult.value = "";
			self.matricoleChecked = [];
		}
		
		this.show = function(idAppello)
	    {
	    	let address = URL_ESAMI_BY_APPELLO + '?id_appello=' + idAppello + "&examState=Non_inserito";
	    	let esamiToShow;
	    	
	      	makeCall("GET", address, null,
	        	function(req)
	        	{
	          		if (req.readyState == XMLHttpRequest.DONE)
	          		{
	            		message = req.responseText;
			            if (req.status == 200)
			            {
				        	esamiToShow = JSON.parse(message);
				        	
				        	if (esamiToShow.length == 0)
			              	{
								alert("Non ci sono esami di cui fare inserimento multiplo.");
			              	}
			              	else
			              	{
						    	self.update(idAppello, esamiToShow); // self is the object on which the function
						    	self.modalDiv.style.display = "block";
							}
			            }
			            else
			            	alert(req.responseText);
	          		}
        		}
	      	);
  		}
  		
  		this.update = function(idAppello, esamiToShow)
	    {	
			emptyElementContent(self.ins_mult_table_body);
			self.voto_mult.value = ""; // empty the new grade field;
			
			self.modalDiv.setAttribute("attribute", idAppello);
			self.assign_mult_button.setAttribute("attribute", idAppello);
			self.closeButton.setAttribute("attribute", idAppello);
		   
		    esamiToShow.forEach(function(esameToShow)
		    { // self visible here, not this
		        row = document.createElement("tr");
		        
		        createTD(row, esameToShow.matricola_studente);
		        createCheckboxTD(row, esameToShow.matricola_studente, 
		        	function(key)
			        {
						key = parseInt(key);
						self.addMatricolaToAssign(key);
					}, 	function(key)
					{
						key = parseInt(key);
						self.removeMatricolaToAssign(key)
					});
		        
		        self.ins_mult_table_body.appendChild(row);
	      	});
	    };
	    
	    this.init = function()
		{
			self.createAssegnamentoMultiploBtnEvent();
			self.createCloseModalWindowBtnEvent();
			self.CreateClickOutsideModalWindowEvent();
		}
	    
	    this.createAssegnamentoMultiploBtnEvent = function()
		{
			this.assign_mult_button.addEventListener("click", (event) =>
			{
				event.preventDefault();
				
				let idAppello = event.target.getAttribute("attribute");
				
				let encodedMatricole = encodeURIComponent(JSON.stringify(self.matricoleChecked));
				
				let newVoto = self.voto_mult.value;
				
				let address = URL_ASSIGN_MULT_GRADE
					+ "?id_appello=" + idAppello
					+ "&matricole=" + encodedMatricole
					+ "&voto=" + newVoto;
				
				makeCall("GET", address, null,
	        	function(req)
		        	{
		          		if (req.readyState == XMLHttpRequest.DONE)
		          		{
		            		message = req.responseText;
		            		
		            		if (req.status == 200)
		            		{
								if(message == "Invalid grade")
					            {
									alert("Hai inserito un voto non valido.");
									pageOrchestrator.showInserimentoMultiplo(idAppello);
								}
								if(message == "No matricole selected")
								{
									alert("Non hai selezionato nessuna matricola.");
									pageOrchestrator.showInserimentoMultiplo(idAppello);
								}
					            else
					            {
						        	pageOrchestrator.showEsami(idAppello)
					            }
							}
							else
								alert(req.responseText);
		          		}
	        		}
	    		);
			}, false);
		}
		
		this.createCloseModalWindowBtnEvent = function()
		{
			// Defines behaviour of button close event
			this.closeButton.addEventListener("click", (event) =>
			{
				pageOrchestrator.showEsami(event.target.getAttribute("attribute"));
			}, false);
		}
  		
  		this.CreateClickOutsideModalWindowEvent = function()
  		{
		  	// Defines bevaviour when clicking outside the modal window
			window.onclick = function(event)
			{
				if (event.target == self.modalDiv)
				{
			    	pageOrchestrator.showEsami(event.target.getAttribute("attribute"));
			  	}
			}
		}
		
		// Adds matricola to list of ones for multiple assignment
		this.addMatricolaToAssign = function(matricola)
  		{
	    	self.matricoleChecked.push(matricola);
		}
		
		// Removes matricola to list of ones for multiple assignment
		this.removeMatricolaToAssign = function(matricola)
  		{
			self.matricoleChecked.pop(matricola);
	  	}
	}
}