package TIW_project.DAO;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.sql.Date;
import java.util.List;
import java.sql.Statement;

import TIW_project.Beans.Verbale;
import TIW_project.Beans.Docente;

public class VerbaleDAO
{
	private Connection connection;
		
	public VerbaleDAO(Connection connection)
	{
		this.connection = connection;
	}
	
	public List<Verbale> getVerbaliById_appello(int id_appello) throws SQLException
	{
List<Verbale> verbali = new ArrayList<>();
		
		String query = ""
				+ "SELECT verbali.id, id_appello, insegnamenti.nome AS nome_insegnamento, datetime\n"
				+ "FROM verbali\n"
				+ "JOIN appelli ON appelli.id = verbali.id_appello\n"
				+ "JOIN scaglioni ON scaglioni.id = appelli.id_scaglioni\n"
				+ "JOIN insegnamenti ON insegnamenti.id = scaglioni.id_insegnamento\n"
				+ "WHERE id_appello = ?";
		
		try (PreparedStatement pstatement = connection.prepareStatement(query);)
		{
			pstatement.setInt(1, id_appello);
			try (ResultSet result = pstatement.executeQuery();)
			{
				while (result.next())
				{	
					int id = result.getInt("id");			
					String nome_insegnamento = result.getString("nome_insegnamento");
					Date datetime = result.getDate("datetime");
					
					verbali.add(new Verbale(id, id_appello, nome_insegnamento, datetime));			
				}
				
				return verbali;
			}
		}
	}
	
	public Verbale getVerbale(int id) throws SQLException
	{
		Verbale verbale = null;
		
		String query = ""
				+ "SELECT verbali.id, id_appello, insegnamenti.nome AS nome_insegnamento, datetime\n"
				+ "FROM verbali\n"
				+ "JOIN appelli ON appelli.id = verbali.id_appello\n"
				+ "JOIN scaglioni ON scaglioni.id = appelli.id_scaglioni\n"
				+ "JOIN insegnamenti ON insegnamenti.id = scaglioni.id_insegnamento\n"
				+ "WHERE verbali.id = ?";
		
		try (PreparedStatement pstatement = connection.prepareStatement(query);)
		{
			pstatement.setInt(1, id);
			try (ResultSet result = pstatement.executeQuery();)
			{
				if (result.next())
				{	
					int id_appello = result.getInt("id_appello");
					String nome_insegnamento = result.getString("nome_insegnamento");
					Date datetime = result.getDate("datetime");
					
					verbale = new Verbale(id, id_appello, nome_insegnamento, datetime);
				}
				return verbale;
			}
		}
	}
	
	//creates verbale and returns its id
	public int createEmptyVerbale(int id_appello) throws SQLException
	{
		String query = ""
				+ "INSERT into verbali (id_appello, datetime)\n"
				+ "VALUES (?,?)";
		
		try (PreparedStatement pstatement = connection.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);)
		{	
			pstatement.setInt(1, id_appello);
			pstatement.setTimestamp(2, new java.sql.Timestamp(new java.util.Date().getTime()));                           
			
			pstatement.executeUpdate();

			ResultSet tableKeys = pstatement.getGeneratedKeys();
			tableKeys.next();
			int autoGeneratedID = tableKeys.getInt(1);
			return autoGeneratedID;
		}
	}
	
	public void populateStudentiVerbale(Verbale verbale) throws SQLException
	{
		String query = ""
				+ "INSERT INTO studenti_verbale (id_verbale, matricola_studente)\n"
				+ "VALUES (?,?)";
		
		EsameDAO esamedao = new EsameDAO(connection);
		List<Integer> matricole = esamedao.getMatricoleDaVerbalizzare(verbale.getId_appello());
		
		
		for (Integer matricola : matricole)
		{
			try (PreparedStatement pstatement = connection.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);)
			{		
				pstatement.setInt(1, verbale.getId());
				pstatement.setInt(2, matricola);    
				
				pstatement.executeUpdate();
			}
		}
		
	}
	
	public boolean verbaleBelongsToTeacher(int idVerbale, Docente docente) throws SQLException {
		String query = "select *\r\n"
				+ "from verbali v join appelli a join scaglioni s\r\n"
				+ "on v.id_appello = a.id and a.id_scaglioni = s.id\r\n"
				+ "where v.id = ? and s.matricola_docente = ?";
		PreparedStatement pstatement = connection.prepareStatement(query);
		pstatement.setInt(1, idVerbale);
		pstatement.setInt(2, docente.getMatricola());
		ResultSet result = pstatement.executeQuery();
		return result.isBeforeFirst();
	}
}